/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nornenjs_android_MprActivity */

#ifndef _Included_com_nornenjs_android_MprActivity
#define _Included_com_nornenjs_android_MprActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_nornenjs_android_MprActivity_BIND_ABOVE_CLIENT
#define com_nornenjs_android_MprActivity_BIND_ABOVE_CLIENT 8L
#undef com_nornenjs_android_MprActivity_BIND_ADJUST_WITH_ACTIVITY
#define com_nornenjs_android_MprActivity_BIND_ADJUST_WITH_ACTIVITY 128L
#undef com_nornenjs_android_MprActivity_BIND_ALLOW_OOM_MANAGEMENT
#define com_nornenjs_android_MprActivity_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef com_nornenjs_android_MprActivity_BIND_AUTO_CREATE
#define com_nornenjs_android_MprActivity_BIND_AUTO_CREATE 1L
#undef com_nornenjs_android_MprActivity_BIND_DEBUG_UNBIND
#define com_nornenjs_android_MprActivity_BIND_DEBUG_UNBIND 2L
#undef com_nornenjs_android_MprActivity_BIND_IMPORTANT
#define com_nornenjs_android_MprActivity_BIND_IMPORTANT 64L
#undef com_nornenjs_android_MprActivity_BIND_NOT_FOREGROUND
#define com_nornenjs_android_MprActivity_BIND_NOT_FOREGROUND 4L
#undef com_nornenjs_android_MprActivity_BIND_WAIVE_PRIORITY
#define com_nornenjs_android_MprActivity_BIND_WAIVE_PRIORITY 32L
#undef com_nornenjs_android_MprActivity_CONTEXT_IGNORE_SECURITY
#define com_nornenjs_android_MprActivity_CONTEXT_IGNORE_SECURITY 2L
#undef com_nornenjs_android_MprActivity_CONTEXT_INCLUDE_CODE
#define com_nornenjs_android_MprActivity_CONTEXT_INCLUDE_CODE 1L
#undef com_nornenjs_android_MprActivity_CONTEXT_RESTRICTED
#define com_nornenjs_android_MprActivity_CONTEXT_RESTRICTED 4L
#undef com_nornenjs_android_MprActivity_MODE_APPEND
#define com_nornenjs_android_MprActivity_MODE_APPEND 32768L
#undef com_nornenjs_android_MprActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define com_nornenjs_android_MprActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef com_nornenjs_android_MprActivity_MODE_MULTI_PROCESS
#define com_nornenjs_android_MprActivity_MODE_MULTI_PROCESS 4L
#undef com_nornenjs_android_MprActivity_MODE_PRIVATE
#define com_nornenjs_android_MprActivity_MODE_PRIVATE 0L
#undef com_nornenjs_android_MprActivity_MODE_WORLD_READABLE
#define com_nornenjs_android_MprActivity_MODE_WORLD_READABLE 1L
#undef com_nornenjs_android_MprActivity_MODE_WORLD_WRITEABLE
#define com_nornenjs_android_MprActivity_MODE_WORLD_WRITEABLE 2L
#undef com_nornenjs_android_MprActivity_DEFAULT_KEYS_DIALER
#define com_nornenjs_android_MprActivity_DEFAULT_KEYS_DIALER 1L
#undef com_nornenjs_android_MprActivity_DEFAULT_KEYS_DISABLE
#define com_nornenjs_android_MprActivity_DEFAULT_KEYS_DISABLE 0L
#undef com_nornenjs_android_MprActivity_DEFAULT_KEYS_SEARCH_GLOBAL
#define com_nornenjs_android_MprActivity_DEFAULT_KEYS_SEARCH_GLOBAL 4L
#undef com_nornenjs_android_MprActivity_DEFAULT_KEYS_SEARCH_LOCAL
#define com_nornenjs_android_MprActivity_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef com_nornenjs_android_MprActivity_DEFAULT_KEYS_SHORTCUT
#define com_nornenjs_android_MprActivity_DEFAULT_KEYS_SHORTCUT 2L
#undef com_nornenjs_android_MprActivity_RESULT_CANCELED
#define com_nornenjs_android_MprActivity_RESULT_CANCELED 0L
#undef com_nornenjs_android_MprActivity_RESULT_FIRST_USER
#define com_nornenjs_android_MprActivity_RESULT_FIRST_USER 1L
#undef com_nornenjs_android_MprActivity_RESULT_OK
#define com_nornenjs_android_MprActivity_RESULT_OK -1L
#undef com_nornenjs_android_MprActivity_VOLUME
#define com_nornenjs_android_MprActivity_VOLUME 0L
#undef com_nornenjs_android_MprActivity_MPRX
#define com_nornenjs_android_MprActivity_MPRX 1L
#undef com_nornenjs_android_MprActivity_MPRY
#define com_nornenjs_android_MprActivity_MPRY 2L
#undef com_nornenjs_android_MprActivity_MPRZ
#define com_nornenjs_android_MprActivity_MPRZ 3L
/*
 * Class:     com_nornenjs_android_MprActivity
 * Method:    nativeOnCreate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_nornenjs_android_MprActivity_nativeOnCreate
  (JNIEnv *, jobject);

/*
 * Class:     com_nornenjs_android_MprActivity
 * Method:    nativeOnPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_nornenjs_android_MprActivity_nativeOnPause
  (JNIEnv *, jobject);

/*
 * Class:     com_nornenjs_android_MprActivity
 * Method:    nativeOnResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_nornenjs_android_MprActivity_nativeOnResume
  (JNIEnv *, jobject);

/*
 * Class:     com_nornenjs_android_MprActivity
 * Method:    nativeOnDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_nornenjs_android_MprActivity_nativeOnDestroy
  (JNIEnv *, jobject);

/*
 * Class:     com_nornenjs_android_MprActivity
 * Method:    nativeOnTrackballEvent
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_com_nornenjs_android_MprActivity_nativeOnTrackballEvent
  (JNIEnv *, jobject, jint, jfloat, jfloat);

/*
 * Class:     com_nornenjs_android_MprActivity
 * Method:    nativeOnTouchEvent
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_com_nornenjs_android_MprActivity_nativeOnTouchEvent
  (JNIEnv *, jobject, jint, jfloat, jfloat);

/*
 * Class:     com_nornenjs_android_MprActivity
 * Method:    nativeInitGL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_nornenjs_android_MprActivity_nativeInitGL
  (JNIEnv *, jobject);

/*
 * Class:     com_nornenjs_android_MprActivity
 * Method:    nativeResize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_nornenjs_android_MprActivity_nativeResize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_nornenjs_android_MprActivity
 * Method:    nativeDrawIteration
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_nornenjs_android_MprActivity_nativeDrawIteration
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     com_nornenjs_android_MprActivity
 * Method:    nativeInitTextureData
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_com_nornenjs_android_MprActivity_nativeInitTextureData
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_nornenjs_android_MprActivity
 * Method:    nativeSetTextureData
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_com_nornenjs_android_MprActivity_nativeSetTextureData
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
