/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nornenjs_android_MprActivity_MPRRenderer */

#ifndef _Included_com_nornenjs_android_MprActivity_MPRRenderer
#define _Included_com_nornenjs_android_MprActivity_MPRRenderer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
